#[derive(thiserror::Error, Debug, Clone)]
pub enum ServerProtocolError {
    #[error("Failed to verify the signature attached to the token.")]
    FailedToVerifyTokenSignature,
    #[error("Failed to encapsulation the key.")]
    EncapsulationFailed,
    #[error("Failed to sign a response.")]
    FailedToSignResponse,
    #[error("Failed to verify that the client cycling actually owns the new key.")]
    FailedToVerifyNewCycleKey,
    #[error("Failed to verify that the client cycling owns the old cycling key.")]
    FailedToVerifyOldKeyDuringCycle,
    #[error("Failed to verify that the k-proof during registration was generated correctly.")]
    FailedToVerifyKProof,
    #[error("Failed to verify that the a-proof during registration was generated by an admin.")]
    FailedToVerifyAProof,
    #[error("The token was rejected because it was not in the specified server time interval")]
    TokenOutOfInterval,
    #[error("The alledged admin claimed by the client does not actually exist")]
    NoAdminFound,
    #[error("The UUID requested for registration is not unique.")]
    UuidTaken,
    #[error("The public key is not unique.")]
    PublicKeyNotUnique,
    #[error("Miscelleaneous error.")]
    Misc(String),
    #[error("Failed to store the key.")]
    StoreFailure(String)
}

#[derive(thiserror::Error, Debug)]
pub enum ClientProtocolError {
    #[error("Failed to generate the digital signing key pair for cycling/registration")]
    FailedToGenerateDsaPair,
    #[error("Failed to generate the decap key/encap key pair.")]
    FailedToGenerateKemPair,
    #[error("Failed to verify the server signature on the cycle request response.")]
    InauthenticCycleResponse,
    #[error("Failed to verify the server signature on the token request response.")]
    InauthenticTokenResponse,
    #[error("Failed to decapsulate the ciphertext.")]
    DecapsulationError,
    #[error("Failed to sign a message with the client private key.")]
    FailedToSignRequest,
    #[error("Failed to generate the k-proof on the original registration request.")]
    KProofSignError,
    #[error("Failed to generate the a-proof on the original registration request.")]
    AProofSignError,
    #[error("Failed to verify the identity hash which is part of the registration process.")]
    FailedToVerifyIdentityHash,
    #[error("Failed to verify the server signature on the register response.")]
    InauthenticRegisterResponse,
    #[error("Failed to verify the hash returned by the server on the cycle response.")]
    FailedToVerifyCycleHash,
    #[error("Failed to verify the approval hash, as in, the exact hash was not reconstructed on the client end.")]
    FailedToReconstructApprovalHash,
    #[error("Server protocol failure.")]
    ServerError(#[from] ServerProtocolError)
}



impl From<ServerProtocolError> for String {
    fn from(value: ServerProtocolError) -> Self {
        value.to_string()
    }
}

impl From<ClientProtocolError> for String {
    fn from(value: ClientProtocolError) -> Self {
        value.to_string()
    }
}


